### ISSUE TITLE
offset gap between tile and lower zoom tiles

### ISSUE THREAD

**Issue by boraerden** [ghybs/Leaflet.TileLayer.Fallback#12]
using leaflet 1.3.3
and Leaflet.TileLayer.Fallback 1.0.4

There is a gap to the left between the tile with the appropriate zoom level and the lower zoom tiles.

![image](https://user-images.githubusercontent.com/7088004/45178614-2ff44e80-b1e4-11e8-8565-d8e152bf5083.png)

Did anyone else have this issue?

**Comment by ghybs** [comment]
Hi,

Thank you for your message and screenshot.

Please could you share a live example that reproduces this issue?
(e.g. using https://leafletjs.com/edit, or JSFiddle, etc.)

I am not sure I totally understand what your screenshot is supposed to show, and whether your issue is about tiles at the current zoom level or lower ones:

![45178614-2ff44e80-b1e4-11e8-8565-d8e152bf5083_annotated](https://user-images.githubusercontent.com/12232803/45468872-08e3d280-b738-11e8-8b12-2dfbaa4505fd.png)

Given that some of your tiles have rounded corners, there is some chance you have some global CSS that applies to Leaflet tiles, and may interfere with their shape and position.

**Comment by ghybs** [comment]
Closing due to lack of feedback
